Repository WildCodeSchool/healthymood-back, pull requests merged in 2020-07, with the labels that each got.

#37 Feature/vue/cat recettes
  public/index.html
  public/manifest.json
  src/App.js
  src/Styles/Form.css
  src/Styles/Icons.css
  src/components/SideBar.js
  src/pages/AddArticle.js
  src/pages/AddPage.js
  src/pages/AddRecipe.js
  src/pages/CategoryArticles.js
  src/pages/CategoryRecipes.js
  src/pages/Ingredients.js
  src/pages/Meals.js
  src/services/API.js
Labels: Correction done

#38 Feature/crud/gestion des utilisateurs
  src/Styles/Form.css
  src/Styles/Users.css
  src/components/ArticleCategoryList.js
  src/components/SideBar.js
  src/components/TopBar.js
  src/hooks/useResourceCollection.js
  src/pages/CategoryArticles.js
  src/pages/Diets.js
  src/pages/Dishes.js
  src/pages/Ingredients.js
  src/pages/Meals.js
  src/pages/Users.js
Labels: Correction done, Reviewed

#48 Feature/hotfix
  src/Styles/Form.css
  src/components/SideBar.js
  src/pages/Articles.js
  src/pages/CategoryArticles.js
  src/pages/EditRecipes.js
  src/pages/Ingredients.js
  src/pages/Pages.js
Labels: Reviewed

#46 Feature/crud/pages
  src/Styles/Editor.css
  src/Styles/EditorForm.css
  src/components/SideBar.js
  src/pages/EditArticle.js
  src/pages/EditPage.js
  src/pages/EditRecipes.js
  src/pages/Ingredients.js
  src/pages/Pages.js
Labels: Correction done, Reviewed

#49 Feature/crud/article
  src/Styles/EditorForm.css
  src/Styles/index.css
  src/pages/Articles.js
  src/pages/EditArticle.js
  src/pages/EditRecipes.js
  src/pages/Recipes.js
Labels: Reviewed

#50 Feature/crud/recette
  debug.log
  package-lock.json
  package.json
  public/index.html
  src/Styles/EditorForm.css
  src/Styles/Home.css
  src/Styles/TopBar.css
  src/Styles/Users.css
  src/Styles/index.css
  src/components/SingleSelect.js
  src/components/TagSelect.js
  src/components/TopBar.js
  src/images/image_placeholder.png
  src/pages/CategoryRecipes.js
  src/pages/EditArticle.js
  src/pages/EditRecipes.js
  src/pages/Home.js
  src/pages/Recipes.js
Labels: Reviewed

#52 Feature/display generic pages
  .env
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  src/App.js
  src/Styles/Editor.css
  src/Styles/EditorForm.css
  src/Styles/Form.css
  src/Styles/Icons.css
  src/Styles/SideBar.css
  src/Styles/Users.css
  src/Styles/index.css
  src/components/ArticleCategoryList.js
  src/components/EditorComponent.js
  src/components/SideBar.js
  src/components/TopBar.js
  src/hooks/useEditor.js
  src/hooks/useFormData.js
  src/images/hm-logo-small.png
  src/index.js
  src/pages/AddArticle.js
  src/pages/AddPage.js
  src/pages/AddRecipe.js
  src/pages/AdminAuth.js
  src/pages/Article.js
  src/pages/Articles.js
  src/pages/CategoryArticles.js
  src/pages/CategoryRecipes.js
  src/pages/Diets.js
  src/pages/Dishes.js
  src/pages/EditArticle.js
  src/pages/EditPage.js
  src/pages/EditRecipes.js
  src/pages/Ingredients.js
  src/pages/Meals.js
  src/pages/Pages.js
  src/pages/Recipes.js
  src/pages/Users.js
  src/services/API.js
Labels: Reviewed

#58 Feature/crud/article
  src/components/SideBar.js
  src/components/TopBar.js
  src/pages/Articles.js
  src/pages/CategoryArticles.js
  src/pages/CategoryRecipes.js
  src/pages/EditArticle.js
  src/pages/EditRecipes.js
Labels: Reviewed

#59 vide de authToken
  src/services/API.js
Labels: Reviewed

#51 Feature/pagination/filter/ingredients
  src/Styles/Form.css
  src/Styles/index.css
  src/components/SideBar.js
  src/components/TopBar.js
  src/hooks/useResourceCollection.js
  src/pages/AdminAuth.js
  src/pages/Articles.js
  src/pages/CategoryArticles.js
  src/pages/CategoryRecipes.js
  src/pages/Diets.js
  src/pages/Dishes.js
  src/pages/EditArticle.js
  src/pages/EditRecipes.js
  src/pages/Ingredients.js
  src/pages/Meals.js
  src/pages/Pages.js
  src/pages/Recipes.js
  src/pages/Users.js
  src/services/API.js
Labels: Reviewed

#57 Feature/hotfix2
  src/Styles/AdminAuth.css
  src/Styles/EditorForm.css
  src/Styles/Form.css
  src/Styles/Home.css
  src/Styles/SideBar.css
  src/Styles/TopBar.css
  src/Styles/index.css
  src/components/TopBar.js
  src/hooks/useResourceCollection.js
  src/pages/AdminAuth.js
  src/pages/Articles.js
  src/pages/CategoryArticles.js
  src/pages/CategoryRecipes.js
  src/pages/Diets.js
  src/pages/Dishes.js
  src/pages/EditPage.js
  src/pages/EditRecipes.js
  src/pages/Home.js
  src/pages/Ingredients.js
  src/pages/Meals.js
  src/pages/Pages.js
  src/pages/Recipes.js
  src/pages/Users.js
Labels: Reviewed

#63 Feature/tinymce/uploadimage
  src/pages/EditArticle.js
  src/pages/EditPage.js
  src/pages/EditRecipes.js
Labels: Reviewed

#62 Feature/regex/slug
  src/Styles/index.css
  src/pages/EditArticle.js
  src/pages/EditPage.js
  src/pages/EditRecipes.js
Labels: Reviewed

#61 Hotfix/recipe infos
  src/Styles/EditorForm.css
  src/pages/EditArticle.js
  src/pages/EditPage.js
  src/pages/EditRecipes.js
  src/pages/Recipes.js
Labels: Reviewed

#65 Last hotfix
  src/pages/Articles.js
  src/pages/EditRecipes.js
  src/pages/Users.js
Labels: Reviewed
